Repository SSUDevelog/EasyVel-Server, pull requests merged in 2023-09, with the labels that each got.

#10 [FIX] 리팩토링 보완
  src/main/java/com/easyvel/server/config/security/BaseAccessDeniedHandler.java
  src/main/java/com/easyvel/server/config/security/BaseAuthenticationEntryPoint.java
  src/main/java/com/easyvel/server/config/security/BaseUserDetailsService.java
  src/main/java/com/easyvel/server/config/security/PasswordEncoderConfiguration.java
  src/main/java/com/easyvel/server/sign/SignController.java
Labels: jinsoo, FIX

#12 [FEAT] launch / tag 기능 구현
  src/main/java/com/easyvel/server/global/dto/PostDto.java
  src/main/java/com/easyvel/server/launch/LaunchController.java
  src/main/java/com/easyvel/server/sign/SignController.java
  src/main/java/com/easyvel/server/tag/TagController.java
  src/main/java/com/easyvel/server/tag/TagRepository.java
  src/main/java/com/easyvel/server/tag/TagService.java
  src/main/java/com/easyvel/server/tag/dto/TagList.java
Labels: FEAT, jinsoo

#14 Feat/#13
  src/main/java/com/easyvel/server/config/security/BaseUserDetailsService.java
  src/main/java/com/easyvel/server/notification/NoticeTarget.java
  src/main/java/com/easyvel/server/notification/Notification.java
  src/main/java/com/easyvel/server/sign/SignService.java
  src/main/java/com/easyvel/server/sign/User.java
  src/main/java/com/easyvel/server/sign/UserRepository.java
  src/main/java/com/easyvel/server/subscribe/Subscribe.java
  src/main/java/com/easyvel/server/subscribe/SubscribeController.java
  src/main/java/com/easyvel/server/subscribe/Target.java
  src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
  src/main/java/com/easyvel/server/tag/Tag.java
  src/main/java/com/easyvel/server/tag/TagController.java
  src/main/java/com/easyvel/server/tag/TagRepository.java
  src/main/java/com/easyvel/server/tag/TagService.java
  src/main/java/com/easyvel/server/tag/dto/TagList.java
Labels: FEAT

#16 [FEAT] 무중단 배포를 위한 준비
  build.gradle
  src/main/java/com/easyvel/server/config/ServerProfileController.java
  src/main/java/com/easyvel/server/config/SwaggerConfiguration.java
Labels: FEAT

#18 [FEAT] CD 환경 구축
  .github/workflows/CD.yml
Labels: FEAT

#24 [FIX] CD script에서 빌드 명령어 및 pull 기준 브랜치 변경
  .github/workflows/CD.yml
Labels: FIX
