Repository SSUDevelog/EasyVel-Server, pull requests merged in 2023-10, with the labels that each got.

#20 [Add] nofication
  .gitignore
  build.gradle
  src/main/java/com/easyvel/server/global/entity/User.java
  src/main/java/com/easyvel/server/notification/NotificationController.java
  src/main/java/com/easyvel/server/notification/bridge/NoticeGroupFcmToken.java
  src/main/java/com/easyvel/server/notification/bridge/NoticeGroupFcmTokenRepository.java
  src/main/java/com/easyvel/server/notification/fcm/FcmService.java
  src/main/java/com/easyvel/server/notification/fcm/FcmToken.java
  src/main/java/com/easyvel/server/notification/fcm/FcmTokenRepository.java
  src/main/java/com/easyvel/server/notification/noticegroup/NoticeGroup.java
  src/main/java/com/easyvel/server/notification/noticegroup/NoticeGroupRepository.java
  src/main/java/com/easyvel/server/sign/SignController.java
  src/main/java/com/easyvel/server/sign/SignService.java
  src/main/java/com/easyvel/server/sign/dto/SignInDto.java
Labels: FEAT, jinsoo

#22 [FIX] add two attrs in validate res
  src/main/java/com/easyvel/server/subscribe/SubscribeController.java
  src/main/java/com/easyvel/server/subscribe/dto/ValidateVelogUserDto.java
  src/main/java/com/easyvel/server/subscribe/service/SubscribeService.java
Labels: FIX

#30 [FEAT] 구글로그인 추가, 태그 API uri 변경
  src/main/java/com/easyvel/server/sign/SignController.java
  src/main/java/com/easyvel/server/sign/google/GoogleAuthService.java
  src/main/java/com/easyvel/server/sign/google/GoogleClient.java
  src/main/java/com/easyvel/server/sign/google/dto/GetGoogleTokenResponse.java
  src/main/java/com/easyvel/server/sign/google/dto/GetTokensRequestBody.java
  src/main/java/com/easyvel/server/sign/google/exception/GoogleAuthServiceException.java
  src/main/java/com/easyvel/server/tag/TagController.java
Labels: FEAT
